title: August Valera
description: Personal website for August Valera
url: "127.0.0.1:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

paginate: 5

gems: [jekyll-paginate]
permalink: /:title.html
